### ISSUE TITLE
Sometimes tries to process its own source code when chunk sizes are small

### ISSUE THREAD

**Issue by chriszs** [tvkitchen/utilities#13]
#### Current Behavior
When fed a chunk smaller than 4KB, [this line](https://github.com/tvkitchen/utilities/blob/fbf67a72b53f108dc715e2f344f98bd6fcb63d12/packages/mpegts-demuxer/src/MpegTsDemuxer.ts#L46) sometimes pulls from a shared buffer, parts of which haven't been cleared, as explained [here](https://stackoverflow.com/a/31394257). In my testing, this sometimes caused the demuxer to try to process its own source code.

#### Input
This is a minimal reproduction:

```js
const bufferA = Buffer.alloc(500);
const bufferB = Buffer.alloc(500);
const bufferC = Buffer.concat([bufferA, bufferB]);
console.log(Buffer.from(bufferC.buffer).toString())
```

#### Expected Behavior
The program does not process its own source code.

#### Possible Solutions
[This StackOverflow answer](https://stackoverflow.com/a/31394257) suggests an approach like this might work:

```js
const mem = new DataView(
	this.unprocessed.buffer.slice(
		this.unprocessed.byteOffset,
		this.unprocessed.byteOffset + this.unprocessed.byteLength
	)
);
```

**Comment by slifty** [comment]
This was a mind bending bug to watch unfold -- thank you for finding it and figuring out what was going on!
